# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sudoku.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sudoku_game(object):
    def setupUi(self, sudoku_game):
        sudoku_game.setObjectName("sudoku_game")
        sudoku_game.resize(862, 637)
        self.centralwidget = QtWidgets.QWidget(sudoku_game)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 581, 581))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.sudoku_table = QtWidgets.QTableWidget(self.frame)
        self.sudoku_table.setGeometry(QtCore.QRect(10, 10, 561, 561))
        self.sudoku_table.setMinimumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sudoku_table.setFont(font)
        self.sudoku_table.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sudoku_table.setFrameShape(QtWidgets.QFrame.Box)
        self.sudoku_table.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sudoku_table.setLineWidth(5)
        self.sudoku_table.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.sudoku_table.setIconSize(QtCore.QSize(0, 0))
        self.sudoku_table.setRowCount(9)
        self.sudoku_table.setColumnCount(9)
        self.sudoku_table.setObjectName("sudoku_table")
        self.sudoku_table.horizontalHeader().setVisible(False)
        self.sudoku_table.horizontalHeader().setDefaultSectionSize(60)
        self.sudoku_table.horizontalHeader().setHighlightSections(True)
        self.sudoku_table.horizontalHeader().setMinimumSectionSize(20)
        self.sudoku_table.verticalHeader().setVisible(False)
        self.sudoku_table.verticalHeader().setDefaultSectionSize(60)
        self.sudoku_table.verticalHeader().setMinimumSectionSize(25)
        self.sudoku_table.verticalHeader().setSortIndicatorShown(True)
        self.sudoku_table.verticalHeader().setStretchLastSection(False)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(20, 192, 538, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.line.setFont(font)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(20, 372, 538, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.line_2.setFont(font)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(5)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(20, 15, 545, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.line_3.setFont(font)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(5)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.frame)
        self.line_4.setGeometry(QtCore.QRect(20, 553, 545, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.line_4.setFont(font)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(5)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.frame)
        self.line_5.setGeometry(QtCore.QRect(370, 23, 20, 534))
        self.line_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_5.setLineWidth(5)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.frame)
        self.line_6.setGeometry(QtCore.QRect(190, 23, 20, 534))
        self.line_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_6.setLineWidth(5)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.frame)
        self.line_7.setGeometry(QtCore.QRect(12, 23, 20, 536))
        self.line_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_7.setLineWidth(5)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.frame)
        self.line_8.setGeometry(QtCore.QRect(552, 23, 20, 536))
        self.line_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_8.setLineWidth(5)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setObjectName("line_8")
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(600, 280, 251, 311))
        self.frame_7.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.frame_7)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 231, 161))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.button_2.setMaximumSize(QtCore.QSize(72, 16777215))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.button_2.setFont(font)
        self.button_2.setObjectName("button_2")
        self.gridLayout_2.addWidget(self.button_2, 0, 1, 1, 1)
        self.button_3 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.button_3.setMaximumSize(QtCore.QSize(72, 16777215))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.button_3.setFont(font)
        self.button_3.setObjectName("button_3")
        self.gridLayout_2.addWidget(self.button_3, 0, 2, 1, 1)
        self.button_4 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.button_4.setMaximumSize(QtCore.QSize(72, 16777215))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.button_4.setFont(font)
        self.button_4.setObjectName("button_4")
        self.gridLayout_2.addWidget(self.button_4, 1, 0, 1, 1)
        self.button_6 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.button_6.setMaximumSize(QtCore.QSize(72, 16777215))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.button_6.setFont(font)
        self.button_6.setObjectName("button_6")
        self.gridLayout_2.addWidget(self.button_6, 1, 2, 1, 1)
        self.button_5 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.button_5.setMaximumSize(QtCore.QSize(72, 16777215))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.button_5.setFont(font)
        self.button_5.setObjectName("button_5")
        self.gridLayout_2.addWidget(self.button_5, 1, 1, 1, 1)
        self.button_1 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.button_1.setMaximumSize(QtCore.QSize(72, 16777215))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.button_1.setFont(font)
        self.button_1.setObjectName("button_1")
        self.gridLayout_2.addWidget(self.button_1, 0, 0, 1, 1)
        self.button_7 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.button_7.setMaximumSize(QtCore.QSize(72, 16777215))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.button_7.setFont(font)
        self.button_7.setObjectName("button_7")
        self.gridLayout_2.addWidget(self.button_7, 2, 0, 1, 1)
        self.button_8 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.button_8.setMaximumSize(QtCore.QSize(72, 16777215))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.button_8.setFont(font)
        self.button_8.setObjectName("button_8")
        self.gridLayout_2.addWidget(self.button_8, 2, 1, 1, 1)
        self.button_9 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.button_9.setMaximumSize(QtCore.QSize(72, 16777215))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.button_9.setFont(font)
        self.button_9.setObjectName("button_9")
        self.gridLayout_2.addWidget(self.button_9, 2, 2, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.frame_7)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 210, 231, 91))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.reset_game = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.reset_game.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.reset_game.setFont(font)
        self.reset_game.setObjectName("reset_game")
        self.gridLayout_3.addWidget(self.reset_game, 1, 0, 1, 1)
        self.undo = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.undo.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.undo.setFont(font)
        self.undo.setObjectName("undo")
        self.gridLayout_3.addWidget(self.undo, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        self.label_5.setGeometry(QtCore.QRect(56, 10, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(600, 150, 251, 121))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.check_errors = QtWidgets.QPushButton(self.frame_2)
        self.check_errors.setGeometry(QtCore.QRect(10, 80, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.check_errors.setFont(font)
        self.check_errors.setObjectName("check_errors")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 231, 61))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.timer_display = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.timer_display.setFont(font)
        self.timer_display.setAlignment(QtCore.Qt.AlignCenter)
        self.timer_display.setObjectName("timer_display")
        self.gridLayout.addWidget(self.timer_display, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.errors_display = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.errors_display.setFont(font)
        self.errors_display.setAlignment(QtCore.Qt.AlignCenter)
        self.errors_display.setObjectName("errors_display")
        self.gridLayout.addWidget(self.errors_display, 1, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(600, 10, 251, 131))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(60, 10, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.formLayoutWidget = QtWidgets.QWidget(self.frame_3)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 40, 225, 70))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.custom_hidden = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.custom_hidden.setMinimumSize(QtCore.QSize(0, 31))
        self.custom_hidden.setMaximum(81)
        self.custom_hidden.setObjectName("custom_hidden")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.custom_hidden)
        self.start_custom_game = QtWidgets.QPushButton(self.formLayoutWidget)
        self.start_custom_game.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.start_custom_game.setFont(font)
        self.start_custom_game.setObjectName("start_custom_game")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.start_custom_game)
        sudoku_game.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(sudoku_game)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 862, 21))
        self.menubar.setObjectName("menubar")
        self.menuNEW_GAME = QtWidgets.QMenu(self.menubar)
        self.menuNEW_GAME.setObjectName("menuNEW_GAME")
        sudoku_game.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(sudoku_game)
        self.statusbar.setObjectName("statusbar")
        sudoku_game.setStatusBar(self.statusbar)
        self.start_easy_game = QtWidgets.QAction(sudoku_game)
        self.start_easy_game.setObjectName("start_easy_game")
        self.start_medium_game = QtWidgets.QAction(sudoku_game)
        self.start_medium_game.setObjectName("start_medium_game")
        self.start_hard_game = QtWidgets.QAction(sudoku_game)
        self.start_hard_game.setObjectName("start_hard_game")
        self.start_stupes_game = QtWidgets.QAction(sudoku_game)
        self.start_stupes_game.setObjectName("start_stupes_game")
        self.menuNEW_GAME.addAction(self.start_easy_game)
        self.menuNEW_GAME.addAction(self.start_medium_game)
        self.menuNEW_GAME.addAction(self.start_hard_game)
        self.menuNEW_GAME.addAction(self.start_stupes_game)
        self.menubar.addAction(self.menuNEW_GAME.menuAction())

        self.retranslateUi(sudoku_game)
        QtCore.QMetaObject.connectSlotsByName(sudoku_game)

    def retranslateUi(self, sudoku_game):
        _translate = QtCore.QCoreApplication.translate
        sudoku_game.setWindowTitle(_translate("sudoku_game", "SUDOKU"))
        self.button_2.setText(_translate("sudoku_game", "2"))
        self.button_3.setText(_translate("sudoku_game", "3"))
        self.button_4.setText(_translate("sudoku_game", "4"))
        self.button_6.setText(_translate("sudoku_game", "6"))
        self.button_5.setText(_translate("sudoku_game", "5"))
        self.button_1.setText(_translate("sudoku_game", "1"))
        self.button_7.setText(_translate("sudoku_game", "7"))
        self.button_8.setText(_translate("sudoku_game", "8"))
        self.button_9.setText(_translate("sudoku_game", "9"))
        self.reset_game.setText(_translate("sudoku_game", "RESET GAME"))
        self.undo.setText(_translate("sudoku_game", "UNDO PREVIOUS STEP"))
        self.label_5.setText(_translate("sudoku_game", "NUMBER ENTRY"))
        self.check_errors.setText(_translate("sudoku_game", "CHECK ERRORS"))
        self.label.setText(_translate("sudoku_game", "GAME TIME:"))
        self.timer_display.setText(_translate("sudoku_game", "00:00:00"))
        self.label_2.setText(_translate("sudoku_game", "ERRORS:"))
        self.errors_display.setText(_translate("sudoku_game", "0"))
        self.label_4.setText(_translate("sudoku_game", "CUSTOM GAME"))
        self.label_3.setText(_translate("sudoku_game", "# OF HIDDEN SQUARES:"))
        self.start_custom_game.setText(_translate("sudoku_game", "START NEW GAME"))
        self.menuNEW_GAME.setTitle(_translate("sudoku_game", "NEW GAME"))
        self.start_easy_game.setText(_translate("sudoku_game", "Easy"))
        self.start_medium_game.setText(_translate("sudoku_game", "Medium"))
        self.start_hard_game.setText(_translate("sudoku_game", "Hard"))
        self.start_stupes_game.setText(_translate("sudoku_game", "Stupes"))
